const detectedConditions = [
  { name: 'Type 2 Diabetes',  icon: 'fa-solid fa-droplet',        color: 'blue'   },
  { name: 'Hypertension',     icon: 'fa-solid fa-heart-pulse',     color: 'red'    },
  { name: 'High Cholesterol', icon: 'fa-solid fa-chart-line',      color: 'orange' },
]

const dietSections = [
  {
    id: '1',
    title: 'Foods to Eat',
    icon: 'fa-solid fa-circle-check',
    color: 'green',
    items: [
      'Leafy greens — spinach, kale, broccoli',
      'Whole grains — oats, brown rice, quinoa',
      'Lean proteins — chicken, fish, legumes',
      'Healthy fats — avocado, olive oil, nuts',
      'Low-glycemic fruits — berries, apples, pears',
      'High-fiber vegetables — carrots, beans, lentils',
    ],
  },
  {
    id: '2',
    title: 'Foods to Avoid',
    icon: 'fa-solid fa-circle-xmark',
    color: 'red',
    items: [
      'Sugary drinks — soda, fruit juices, energy drinks',
      'Refined carbs — white bread, pastries, white rice',
      'Saturated fats — red meat, butter, full-fat dairy',
      'High-sodium foods — processed meats, canned soups',
      'Alcohol — raises blood sugar and blood pressure',
      'Fried foods — chips, fast food, deep-fried items',
    ],
  },
  {
    id: '3',
    title: 'Lifestyle Tips',
    icon: 'fa-solid fa-person-walking',
    color: 'blue',
    items: [
      'Walk 30 minutes daily — helps control blood sugar',
      'Stay hydrated — drink 8 glasses of water per day',
      'Eat smaller meals — 5-6 small meals vs 3 large',
      'Monitor blood pressure weekly at home',
      'Get 7-8 hours of sleep consistently',
      'Reduce stress — try meditation or deep breathing',
    ],
  },
  {
    id: '4',
    title: 'Medication Interactions',
    icon: 'fa-solid fa-triangle-exclamation',
    color: 'orange',
    items: [
      'Metformin: take with food to reduce stomach upset',
      'Lisinopril: avoid potassium supplements or salt substitutes',
      'Atorvastatin: avoid grapefruit and grapefruit juice',
      'Aspirin: avoid on empty stomach — take with food or milk',
    ],
  },
]

const mealPlan = [
  { meal: 'Breakfast',    time: '7:00 AM',  suggestion: 'Oatmeal with berries + green tea' },
  { meal: 'Mid-morning',  time: '10:00 AM', suggestion: 'Apple slices with almond butter' },
  { meal: 'Lunch',        time: '1:00 PM',  suggestion: 'Grilled chicken salad with olive oil dressing' },
  { meal: 'Afternoon',    time: '4:00 PM',  suggestion: 'Handful of mixed nuts + water' },
  { meal: 'Dinner',       time: '7:00 PM',  suggestion: 'Baked salmon with steamed broccoli + quinoa' },
]

// ─── Color Maps ───────────────────────────────────────────────────────────────

type Color = 'blue' | 'red' | 'orange' | 'green'

const conditionPillClass: Record<Color, string> = {
  blue:   'bg-blue-50   text-blue-700   border-blue-200',
  red:    'bg-red-50    text-red-700    border-red-200',
  orange: 'bg-orange-50 text-orange-700 border-orange-200',
  green:  'bg-green-50  text-green-700  border-green-200',
}

const sectionIconBg: Record<Color, string> = {
  green:  'bg-green-50',
  red:    'bg-red-50',
  blue:   'bg-blue-50',
  orange: 'bg-orange-50',
}

const sectionIconText: Record<Color, string> = {
  green:  'text-green-600',
  red:    'text-red-600',
  blue:   'text-blue-600',
  orange: 'text-orange-500',
}

const sectionDot: Record<Color, string> = {
  green:  'bg-green-400',
  red:    'bg-red-400',
  blue:   'bg-blue-400',
  orange: 'bg-orange-400',
}


export default function Diet() {
  return (
    <div className="space-y-6">
      {/* DISCLAIMER */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex items-start gap-3">
        <i className="fa-solid fa-circle-info text-amber-600 mt-0.5 shrink-0" />
        <p className="text-sm text-amber-800">
          These recommendations are AI-generated based on your medications. Always consult your
          doctor or a registered dietitian before making dietary changes.
        </p>
      </div>
      {/* 1. PAGE HEADER */}
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Diet &amp; Health</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            Personalized recommendations based on your medications
          </p>
        </div>
        <span className="inline-flex items-center gap-1.5 bg-purple-50 text-purple-600 border border-purple-200 rounded-full px-3 py-1 text-xs">
          <i className="fa-solid fa-wand-magic-sparkles" />
          Generated by AI · Gemini AI
        </span>
      </div>

      {/* 2. DETECTED CONDITIONS */}
      <div>
        <p className="text-sm font-semibold text-gray-700 mb-3">Detected Conditions</p>
        <div className="flex flex-wrap gap-2">
          {detectedConditions.map(c => (
            <span
              key={c.name}
              className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm ${conditionPillClass[c.color as Color]}`}
            >
              <i className={c.icon} />
              {c.name}
            </span>
          ))}
        </div>
      </div>

      {/* 3. DIET SECTIONS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {dietSections.map(section => (
          <div key={section.id} className="bg-white rounded-xl shadow-sm p-5">
            {/* Header */}
            <div className="flex items-center gap-3">
              <div className={`rounded-full p-2 ${sectionIconBg[section.color as Color]}`}>
                <i className={`${section.icon} ${sectionIconText[section.color as Color]}`} />
              </div>
              <h3 className="font-semibold text-gray-800">{section.title}</h3>
            </div>

            {/* Items */}
            <ul className="mt-3 space-y-2">
              {section.items.map((item, idx) => (
                <li key={idx} className="flex gap-2 items-start text-sm text-gray-600">
                  <span
                    className={`w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0 ${sectionDot[section.color as Color]}`}
                  />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* 4. SAMPLE MEAL PLAN */}
      <div className="bg-white rounded-xl shadow-sm p-5">
        <div className="flex items-center gap-2 mb-1">
          <i className="fa-solid fa-utensils text-gray-700" />
          <h3 className="font-semibold text-gray-800">Sample Meal Plan</h3>
        </div>

        <div className="divide-y divide-gray-100">
          {mealPlan.map(entry => (
            <div key={entry.meal} className="flex items-center py-3">
              <span className="font-medium text-gray-800 w-28 shrink-0">{entry.meal}</span>
              <span className="bg-gray-100 text-gray-600 text-xs px-2 py-0.5 rounded-full shrink-0">
                {entry.time}
              </span>
              <span className="text-sm text-gray-600 flex-1 ml-4">{entry.suggestion}</span>
            </div>
          ))}
        </div>
      </div>



    </div>
  )
}