import { useEffect, useState } from 'react'

type Condition = { name: string; icon: string; color: string }
type Meal = { m: string; t: string; s: string }
type DietData = {
  conditions: Condition[]
  eat: string[]
  avoid: string[]
  meals: Meal[]
}

// ─── Color Maps ───────────────────────────────────────────────────────────────

type Color = 'blue' | 'red' | 'orange' | 'green'

const conditionPillClass: Record<Color, string> = {
  blue:   'bg-blue-50   text-blue-700   border-blue-200',
  red:    'bg-red-50    text-red-700    border-red-200',
  orange: 'bg-orange-50 text-orange-700 border-orange-200',
  green:  'bg-green-50  text-green-700  border-green-200',
}

const sectionIconBg: Record<Color, string> = {
  green:  'bg-green-50',
  red:    'bg-red-50',
  blue:   'bg-blue-50',
  orange: 'bg-orange-50',
}

const sectionIconText: Record<Color, string> = {
  green:  'text-green-600',
  red:    'text-red-600',
  blue:   'text-blue-600',
  orange: 'text-orange-500',
}

const sectionDot: Record<Color, string> = {
  green:  'bg-green-400',
  red:    'bg-red-400',
  blue:   'bg-blue-400',
  orange: 'bg-orange-400',
}


export default function Diet() {
  const [data, setData] = useState<DietData | null>(null)
  const [loading, setLoading] = useState(true)
  const [error, setError] = useState<string | null>(null)
  const [regenerating, setRegenerating] = useState(false)

  useEffect(() => {
    fetch('http://localhost:5001/api/diet-recommendations')
      .then(r => r.json())
      .then((json: DietData) => { setData(json); setLoading(false) })
      .catch(() => { setError('Failed to load recommendations'); setLoading(false) })
  }, [])

  function regenerateMeals() {
    setRegenerating(true)
    fetch('http://localhost:5001/api/meal-plan/regenerate', { method: 'POST' })
      .then(r => r.json())
      .then((json: { meals: Meal[] }) => {
        setData(prev => prev ? { ...prev, meals: json.meals } : prev)
      })
      .finally(() => setRegenerating(false))
  }

  const detectedConditions = data?.conditions ?? []
  const dietSections = [
    {
      id: '1',
      title: 'Foods to Eat',
      icon: 'fa-solid fa-circle-check',
      color: 'green' as Color,
      items: data?.eat ?? [],
    },
    {
      id: '2',
      title: 'Foods to Avoid',
      icon: 'fa-solid fa-circle-xmark',
      color: 'red' as Color,
      items: data?.avoid ?? [],
    },
  ]
  const mealPlan = data?.meals ?? []

  return (
    <div className="space-y-6">
      {/* LOADING / ERROR */}
      {loading && (
        <div className="text-center text-gray-500 py-10">Loading recommendations…</div>
      )}
      {error && (
        <div className="bg-red-50 border border-red-200 rounded-xl p-4 text-red-700 text-sm">{error}</div>
      )}

      {/* DISCLAIMER */}
      <div className="bg-amber-50 border border-amber-200 rounded-xl p-4 flex items-start gap-3">
        <i className="fa-solid fa-circle-info text-amber-600 mt-0.5 shrink-0" />
        <p className="text-sm text-amber-800">
          These recommendations are AI-generated based on your medications. Always consult your
          doctor or a registered dietitian before making dietary changes.
        </p>
      </div>
      {/* 1. PAGE HEADER */}
      <div className="flex items-start justify-between flex-wrap gap-3">
        <div>
          <h1 className="text-2xl font-bold text-gray-800">Diet &amp; Health</h1>
          <p className="text-sm text-gray-500 mt-0.5">
            Personalized recommendations based on your medications
          </p>
        </div>
        <span className="inline-flex items-center gap-1.5 bg-purple-50 text-purple-600 border border-purple-200 rounded-full px-3 py-1 text-xs">
          <i className="fa-solid fa-wand-magic-sparkles" />
          Generated by AI · Gemini AI
        </span>
      </div>

      {/* 2. DETECTED CONDITIONS */}
      <div>
        <p className="text-sm font-semibold text-gray-700 mb-3">Detected Conditions</p>
        <div className="flex flex-wrap gap-2">
          {detectedConditions.map(c => (
            <span
              key={c.name}
              className={`inline-flex items-center gap-2 rounded-full border px-4 py-2 text-sm ${conditionPillClass[c.color as Color]}`}
            >
              <i className={c.icon} />
              {c.name}
            </span>
          ))}
        </div>
      </div>

      {/* 3. DIET SECTIONS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {dietSections.map(section => (
          <div key={section.id} className="bg-white rounded-xl shadow-sm p-5">
            {/* Header */}
            <div className="flex items-center gap-3">
              <div className={`rounded-full p-2 ${sectionIconBg[section.color as Color]}`}>
                <i className={`${section.icon} ${sectionIconText[section.color as Color]}`} />
              </div>
              <h3 className="font-semibold text-gray-800">{section.title}</h3>
            </div>

            {/* Items */}
            <ul className="mt-3 space-y-2">
              {section.items.map((item, idx) => (
                <li key={idx} className="flex gap-2 items-start text-sm text-gray-600">
                  <span
                    className={`w-1.5 h-1.5 rounded-full mt-1.5 flex-shrink-0 ${sectionDot[section.color as Color]}`}
                  />
                  {item}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>

      {/* 4. SAMPLE MEAL PLAN */}
      <div className="bg-white rounded-xl shadow-sm p-5">
        <div className="flex items-center justify-between mb-1">
          <div className="flex items-center gap-2">
            <i className="fa-solid fa-utensils text-gray-700" />
            <h3 className="font-semibold text-gray-800">Sample Meal Plan</h3>
          </div>
          <button
            onClick={regenerateMeals}
            disabled={regenerating}
            className="inline-flex items-center gap-1.5 border border-gray-300 rounded-lg px-3 py-1.5 text-xs text-gray-600 hover:bg-gray-50 disabled:opacity-50 disabled:cursor-not-allowed"
          >
            <i className={`fa-solid fa-arrows-rotate ${regenerating ? 'animate-spin' : ''}`} />
            Regenerate
          </button>
        </div>

        <div className={`divide-y divide-gray-100 transition-opacity ${regenerating ? 'opacity-50' : ''}`}>
          {mealPlan.map(entry => (
            <div key={entry.m} className="flex items-center py-3">
              <span className="font-medium text-gray-800 w-28 shrink-0">{entry.m}</span>
              <span className="bg-gray-100 text-gray-600 text-xs px-2 py-0.5 rounded-full shrink-0">
                {entry.t}
              </span>
              <span className="text-sm text-gray-600 flex-1 ml-4">{entry.s}</span>
            </div>
          ))}
        </div>
      </div>



    </div>
  )
}